# Generated by Django 2.2 on 2019-05-05 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_auto_20190505_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_answers',
        ),
    ]
