# Generated by Django 2.2 on 2019-05-04 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('alunos', models.ManyToManyField(related_name='turmas_onde_sou_aluno', to=settings.AUTH_USER_MODEL)),
                ('professores', models.ManyToManyField(related_name='turmas_onde_sou_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_verbal_linguistica', models.FloatField()),
                ('int_musical', models.FloatField()),
                ('int_logico_matematica', models.FloatField()),
                ('int_cinestesico_corporal', models.FloatField()),
                ('int_espacial_visual', models.FloatField()),
                ('int_intrapessoal', models.FloatField()),
                ('int_naturalista', models.FloatField()),
                ('int_interpessoal', models.FloatField()),
                ('ea_ativo', models.FloatField()),
                ('ea_reflexivo', models.FloatField()),
                ('ea_pragmatico', models.FloatField()),
                ('ea_teorico', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
