# Generated by Django 2.2 on 2019-07-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0002_delete_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='f_est',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='f_int',
            field=models.BooleanField(default=False),
        ),
    ]
